[package]
name = "keo"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.13.1"

[dev-dependencies]
snforge_std = "0.52.0"

[[target.starknet-contract]]
sierra = true

[scripts]
test = "snforge test"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]
